services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Exposes the Vite development server on localhost
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
